services:

  databse:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: marketplacedb
      POSTGRES_USER: marketplace_user
      POSTGRES_PASSWORD: marketplace_password

  storage:
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z-cpuv1
    command: 'server /data --console-address ":9001"'
    ports:
      - 9000:9000
      - 9001:9001