spring:
  application:
    name: marketspace-api
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  jackson:
    deserialization:
      fail-on-unknown-properties: true


api:
  security:
    token:
      secret: ${TOKEN_SECRET}
      expiration-time: ${TOKEN_EXPIRATION_TIME:60} # 1h in minuts

  storage:
    minio:
      url: ${MINIO_URL}
      accessKey: ${MINIO_ACCESS_KEY}
      accessSecret: ${MINIO_ACCESS_SECRET}